name: build-and-deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.75.1'
          extended: true
      - run: npm install postcss-cli
      - run: npm install
      - name: Build
        # remove --minify tag if you do not need itasdfsadfas 
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          repository: '15669072513/layotto'
          path: "./layotto"

      - run: ls layotto && cd layotto &&  npm install && npm run build --config docs && mv  docs/build/* ../public/layotto && ls ../public/layotto

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: 15669072513/mosn.github.io
          publish_dir: ./public
          publish_branch: master
          
#      - name: Pushes to another repository
#        uses: cpina/github-action-push-to-another-repository@main
#        env:
#          SSH_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#        with:
#          source-directory: 'public'
#          destination-github-username: '15669072513'
#          destination-repository-name: 'mosn.github.io'
#          target-branch: master
